/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_ntnu_ttk4145_recs_driver_Driver */

#ifndef _Included_edu_ntnu_ttk4145_recs_driver_Driver
#define _Included_edu_ntnu_ttk4145_recs_driver_Driver
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_ntnu_ttk4145_recs_driver_Driver_NUMBER_OF_FLOORS
#define edu_ntnu_ttk4145_recs_driver_Driver_NUMBER_OF_FLOORS 4L
#undef edu_ntnu_ttk4145_recs_driver_Driver_PORT0
#define edu_ntnu_ttk4145_recs_driver_Driver_PORT0 1L
#undef edu_ntnu_ttk4145_recs_driver_Driver_PORT1
#define edu_ntnu_ttk4145_recs_driver_Driver_PORT1 2L
#undef edu_ntnu_ttk4145_recs_driver_Driver_PORT2
#define edu_ntnu_ttk4145_recs_driver_Driver_PORT2 3L
#undef edu_ntnu_ttk4145_recs_driver_Driver_PORT3
#define edu_ntnu_ttk4145_recs_driver_Driver_PORT3 3L
#undef edu_ntnu_ttk4145_recs_driver_Driver_PORT4
#define edu_ntnu_ttk4145_recs_driver_Driver_PORT4 3L
#undef edu_ntnu_ttk4145_recs_driver_Driver_MOTOR
#define edu_ntnu_ttk4145_recs_driver_Driver_MOTOR 256L
#undef edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_DOWN2
#define edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_DOWN2 512L
#undef edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_UP3
#define edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_UP3 513L
#undef edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_DOWN3
#define edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_DOWN3 514L
#undef edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_DOWN4
#define edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_DOWN4 515L
#undef edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_SENSOR1
#define edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_SENSOR1 516L
#undef edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_SENSOR2
#define edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_SENSOR2 517L
#undef edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_SENSOR3
#define edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_SENSOR3 518L
#undef edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_SENSOR4
#define edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_SENSOR4 519L
#undef edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_IND1
#define edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_IND1 768L
#undef edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_IND2
#define edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_IND2 769L
#undef edu_ntnu_ttk4145_recs_driver_Driver_DOOR_OPEN
#define edu_ntnu_ttk4145_recs_driver_Driver_DOOR_OPEN 771L
#undef edu_ntnu_ttk4145_recs_driver_Driver_LIGHT_DOWN4
#define edu_ntnu_ttk4145_recs_driver_Driver_LIGHT_DOWN4 772L
#undef edu_ntnu_ttk4145_recs_driver_Driver_LIGHT_DOWN3
#define edu_ntnu_ttk4145_recs_driver_Driver_LIGHT_DOWN3 773L
#undef edu_ntnu_ttk4145_recs_driver_Driver_LIGHT_UP3
#define edu_ntnu_ttk4145_recs_driver_Driver_LIGHT_UP3 774L
#undef edu_ntnu_ttk4145_recs_driver_Driver_LIGHT_DOWN2
#define edu_ntnu_ttk4145_recs_driver_Driver_LIGHT_DOWN2 775L
#undef edu_ntnu_ttk4145_recs_driver_Driver_LIGHT_UP2
#define edu_ntnu_ttk4145_recs_driver_Driver_LIGHT_UP2 776L
#undef edu_ntnu_ttk4145_recs_driver_Driver_LIGHT_UP1
#define edu_ntnu_ttk4145_recs_driver_Driver_LIGHT_UP1 777L
#undef edu_ntnu_ttk4145_recs_driver_Driver_LIGHT_COMMAND4
#define edu_ntnu_ttk4145_recs_driver_Driver_LIGHT_COMMAND4 778L
#undef edu_ntnu_ttk4145_recs_driver_Driver_LIGHT_COMMAND3
#define edu_ntnu_ttk4145_recs_driver_Driver_LIGHT_COMMAND3 779L
#undef edu_ntnu_ttk4145_recs_driver_Driver_LIGHT_COMMAND2
#define edu_ntnu_ttk4145_recs_driver_Driver_LIGHT_COMMAND2 780L
#undef edu_ntnu_ttk4145_recs_driver_Driver_LIGHT_COMMAND1
#define edu_ntnu_ttk4145_recs_driver_Driver_LIGHT_COMMAND1 781L
#undef edu_ntnu_ttk4145_recs_driver_Driver_LIGHT_STOP
#define edu_ntnu_ttk4145_recs_driver_Driver_LIGHT_STOP 782L
#undef edu_ntnu_ttk4145_recs_driver_Driver_MOTORDIR
#define edu_ntnu_ttk4145_recs_driver_Driver_MOTORDIR 783L
#undef edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_UP2
#define edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_UP2 784L
#undef edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_UP1
#define edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_UP1 785L
#undef edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_COMMAND4
#define edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_COMMAND4 786L
#undef edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_COMMAND3
#define edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_COMMAND3 787L
#undef edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_COMMAND2
#define edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_COMMAND2 788L
#undef edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_COMMAND1
#define edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_COMMAND1 789L
#undef edu_ntnu_ttk4145_recs_driver_Driver_STOP
#define edu_ntnu_ttk4145_recs_driver_Driver_STOP 790L
#undef edu_ntnu_ttk4145_recs_driver_Driver_OBSTRUCTION
#define edu_ntnu_ttk4145_recs_driver_Driver_OBSTRUCTION 791L
#undef edu_ntnu_ttk4145_recs_driver_Driver_LIGHT_DOWN1
#define edu_ntnu_ttk4145_recs_driver_Driver_LIGHT_DOWN1 -1L
#undef edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_DOWN1
#define edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_DOWN1 -1L
#undef edu_ntnu_ttk4145_recs_driver_Driver_LIGHT_UP4
#define edu_ntnu_ttk4145_recs_driver_Driver_LIGHT_UP4 -1L
#undef edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_UP4
#define edu_ntnu_ttk4145_recs_driver_Driver_FLOOR_UP4 -1L
/*
 * Class:     edu_ntnu_ttk4145_recs_driver_Driver
 * Method:    io_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_ntnu_ttk4145_recs_driver_Driver_io_1init
  (JNIEnv *, jobject);

/*
 * Class:     edu_ntnu_ttk4145_recs_driver_Driver
 * Method:    io_close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_ntnu_ttk4145_recs_driver_Driver_io_1close
  (JNIEnv *, jobject);

/*
 * Class:     edu_ntnu_ttk4145_recs_driver_Driver
 * Method:    io_read_bit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_ntnu_ttk4145_recs_driver_Driver_io_1read_1bit
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_ntnu_ttk4145_recs_driver_Driver
 * Method:    io_set_bit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_ntnu_ttk4145_recs_driver_Driver_io_1set_1bit
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_ntnu_ttk4145_recs_driver_Driver
 * Method:    io_clear_bit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_ntnu_ttk4145_recs_driver_Driver_io_1clear_1bit
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_ntnu_ttk4145_recs_driver_Driver
 * Method:    io_read_analog
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_ntnu_ttk4145_recs_driver_Driver_io_1read_1analog
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_ntnu_ttk4145_recs_driver_Driver
 * Method:    io_write_analog
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_edu_ntnu_ttk4145_recs_driver_Driver_io_1write_1analog
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
